apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-management
  labels:
    app: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app : patient-management
  template:
    metadata:
      labels:
        app: patient-management
    spec:
      containers:
        - name: patient-management
          image: thuji98/patient-management:1.0.8
          imagePullPolicy: Always
          ports:
            - containerPort: 9013

---

apiVersion: v1
kind: Service
metadata:
  name:  patient-management
spec:
  selector:
    app:  patient-management
  ports:
    - nodePort: 30171
      port: 9013
      targetPort: 9013
      protocol: TCP
  type: NodePort