apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  name: logs-patient-management-pv-default
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 4Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: logs-patient-management-pv-claim-default
    namespace: default
  nfs:
    path: "/srv/nfsshare"
    server: 192.168.8.114
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-management
  labels:
    app: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app : patient-management
  template:
    metadata:
      labels:
        app: patient-management
    spec:
      volumes:
        - name: patient-management-volume
          persistentVolumeClaim:
            claimName: logs-patient-management-pv-claim-default
      containers:
        - name: patient-management
          image: thuji98/patient-management
          imagePullPolicy: Always
          ports:
            - containerPort: 9013
          volumeMounts:
            - name: patient-management-volume
              mountPath: /nfsshare

---

apiVersion: v1
kind: Service
metadata:
  name:  patient-management
spec:
  selector:
    app:  patient-management
  ports:
    - nodePort: 30171
      port: 9013
      targetPort: 9013
      protocol: TCP
  type: NodePort