apiVersion: v1
kind: PersistentVolume
metadata:
  name: patient-management-pv
  namespace: default
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.8.114
    path: "/srv/nfsshare/msa"
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patient-management-pvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      purpose: patient-management-logs
  volumeName: patient-management-pv
  volumeMode: Filesystem

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-management
  namespace: default
  labels:
    app: patient-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app : patient-management
  template:
    metadata:
      labels:
        app: patient-management
    spec:
      volumes:
        - name: patient-management-logs
          persistentVolumeClaim:
            claimName: patient-management-pvc
      containers:
        - name: patient-management
          image: thuji98/patient-management
          imagePullPolicy: Always
          ports:
            - containerPort: 9013
          volumeMounts:
            - name: patient-management-logs
              mountPath: /logs
          env:
            - name: TZ
              value: Asia/Colombo
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid

---

apiVersion: v1
kind: Service
metadata:
  name:  patient-management
spec:
  selector:
    app:  patient-management
  ports:
    - nodePort: 30171
      port: 9013
      targetPort: 9013
      protocol: TCP
  type: NodePort